apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-config
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  {{- with .Values.pvc.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.pvc.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
