apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "country-api.fullname" . }}-network-policy
  labels:
    {{- include "country-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "country-api.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: TCP
      port: 443
  - ports:
    - protocol: UDP
      port: 53