apiVersion: v1
kind: Service
metadata:
  name: {{ include "country-api.fullname" . }}
  labels:
    {{- include "country-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api-service
      protocol: TCP
      name: http
  selector:
    {{- include "country-api.selectorLabels" . | nindent 4 }}
