apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "samba.fullname" . }}
  labels:
    {{- include "samba.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "samba.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "samba.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: service-port
              containerPort: {{ .Values.service.port }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.secretRefs.sambaCreds.name }}
                  key: {{ .Values.secretRefs.sambaCreds.usernameKey }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.secretRefs.sambaCreds.name }}
                  key: {{ .Values.secretRefs.sambaCreds.passwordKey }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}

