apiVersion: v1
kind: Service
metadata:
  name: {{ include "samba.fullname" . }}
  labels:
    {{- include "samba.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort}}
{{- end }}
      targetPort: {{ .Values.service.port }}
      name: service-port
  selector:
    {{- include "samba.selectorLabels" . | nindent 4 }}
